baseURL = 'https://yydcnjjw.github.io/'
languageCode = 'en-us'
title = 'yydcnjjw'

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[markup.goldmark.renderer]
  unsafe = true
